export type CountryCallingCode = {
  country: string;
  dialCode: string;
};

export const countryCallingCodes: CountryCallingCode[] = [
  { country: 'Afghanistan', dialCode: '93' },
  { country: 'Albania', dialCode: '355' },
  { country: 'Algeria', dialCode: '213' },
  { country: 'American Samoa', dialCode: '1684' },
  { country: 'Andorra', dialCode: '376' },
  { country: 'Angola', dialCode: '244' },
  { country: 'Anguilla', dialCode: '1264' },
  { country: 'Antarctica', dialCode: '672' },
  { country: 'Antarctica', dialCode: '64' },
  { country: 'Antigua and Barbuda', dialCode: '1268' },
  { country: 'Argentina', dialCode: '54' },
  { country: 'Armenia', dialCode: '374' },
  { country: 'Aruba', dialCode: '297' },
  { country: 'Ascension Island', dialCode: '247' },
  { country: 'Australia', dialCode: '61' },
  { country: 'Austria', dialCode: '43' },
  { country: 'Azerbaijan', dialCode: '994' },
  { country: 'Bahamas', dialCode: '1242' },
  { country: 'Bahrain', dialCode: '973' },
  { country: 'Bangladesh', dialCode: '880' },
  { country: 'Barbados', dialCode: '1246' },
  { country: 'Belarus', dialCode: '375' },
  { country: 'Belgium', dialCode: '32' },
  { country: 'Belize', dialCode: '501' },
  { country: 'Benin', dialCode: '229' },
  { country: 'Bermuda', dialCode: '1441' },
  { country: 'Bhutan', dialCode: '975' },
  { country: 'Bolivia', dialCode: '591' },
  { country: 'Bosnia and Herzegovina', dialCode: '387' },
  { country: 'Botswana', dialCode: '267' },
  { country: 'Brazil', dialCode: '55' },
  { country: 'British Virgin Islands', dialCode: '1284' },
  { country: 'Brunei', dialCode: '673' },
  { country: 'Bulgaria', dialCode: '359' },
  { country: 'Burkina Faso', dialCode: '226' },
  { country: 'Burma (Myanmar)', dialCode: '95' },
  { country: 'Burundi', dialCode: '257' },
  { country: 'Cambodia', dialCode: '855' },
  { country: 'Cameroon', dialCode: '237' },
  { country: 'Canada', dialCode: '1' },
  { country: 'Cape Verde', dialCode: '238' },
  { country: 'Cayman Islands', dialCode: '1345' },
  { country: 'Central African Republic', dialCode: '236' },
  { country: 'Chad', dialCode: '235' },
  { country: 'Chile', dialCode: '56' },
  { country: 'China', dialCode: '86' },
  { country: 'Christmas Island', dialCode: '61' },
  { country: 'Cocos (Keeling) Islands', dialCode: '61' },
  { country: 'Colombia', dialCode: '57' },
  { country: 'Comoros', dialCode: '269' },
  { country: 'Congo', dialCode: '242' },
  { country: 'Cook Islands', dialCode: '682' },
  { country: 'Costa Rica', dialCode: '506' },
  { country: 'Croatia', dialCode: '385' },
  { country: 'Cuba', dialCode: '53' },
  { country: 'Cyprus', dialCode: '357' },
  { country: 'Czech Republic', dialCode: '420' },
  { country: 'Democratic Republic of the Congo', dialCode: '243' },
  { country: 'Denmark', dialCode: '45' },
  { country: 'Diego Garcia', dialCode: '246' },
  { country: 'Djibouti', dialCode: '253' },
  { country: 'Dominica', dialCode: '1767' },
  { country: 'Dominican Republic', dialCode: '1809' },
  { country: 'Dominican Republic', dialCode: '1829' },
  { country: 'Dominican Republic', dialCode: '1849' },
  { country: 'Ecuador', dialCode: '593' },
  { country: 'Egypt', dialCode: '20' },
  { country: 'El Salvador', dialCode: '503' },
  { country: 'Equatorial Guinea', dialCode: '240' },
  { country: 'Eritrea', dialCode: '291' },
  { country: 'Estonia', dialCode: '372' },
  { country: 'Ethiopia', dialCode: '251' },
  { country: 'Falkland Islands', dialCode: '500' },
  { country: 'Faroe Islands', dialCode: '298' },
  { country: 'Fiji', dialCode: '679' },
  { country: 'Finland', dialCode: '358' },
  { country: 'France', dialCode: '33' },
  { country: 'French Guiana', dialCode: '594' },
  { country: 'French Polynesia', dialCode: '689' },
  { country: 'Gabon', dialCode: '241' },
  { country: 'Gambia', dialCode: '220' },
  { country: 'Georgia', dialCode: '995' },
  { country: 'Germany', dialCode: '49' },
  { country: 'Ghana', dialCode: '233' },
  { country: 'Gibraltar', dialCode: '350' },
  { country: 'Greece', dialCode: '30' },
  { country: 'Greenland', dialCode: '299' },
  { country: 'Grenada', dialCode: '1473' },
  { country: 'Guadeloupe', dialCode: '590' },
  { country: 'Guam', dialCode: '1671' },
  { country: 'Guatemala', dialCode: '502' },
  { country: 'Guinea', dialCode: '224' },
  { country: 'Guinea-Bissau', dialCode: '245' },
  { country: 'Guyana', dialCode: '592' },
  { country: 'Haiti', dialCode: '509' },
  { country: 'Holy See (Vatican City)', dialCode: '39' },
  { country: 'Honduras', dialCode: '504' },
  { country: 'Hong Kong', dialCode: '852' },
  { country: 'Hungary', dialCode: '36' },
  { country: 'India', dialCode: '91' },
  { country: 'Indonesia', dialCode: '62' },
  { country: 'Iran', dialCode: '98' },
  { country: 'Iraq', dialCode: '964' },
  { country: 'Ireland', dialCode: '353' },
  { country: 'Isle of Man', dialCode: '44' },
  { country: 'Israel', dialCode: '972' },
  { country: 'Italy', dialCode: '39' },
  { country: "Ivory Coast (Côte d'Ivoire)", dialCode: '225' },
  { country: 'Jamaica', dialCode: '1876' },
  { country: 'Japan', dialCode: '81' },
  { country: 'Jersey', dialCode: '44' },
  { country: 'Jordan', dialCode: '962' },
  { country: 'Kazakhstan', dialCode: '7' },
  { country: 'Kenya', dialCode: '254' },
  { country: 'Kiribati', dialCode: '686' },
  { country: 'Kuwait', dialCode: '965' },
  { country: 'Kyrgyzstan', dialCode: '996' },
  { country: 'Laos', dialCode: '856' },
  { country: 'Latvia', dialCode: '371' },
  { country: 'Lebanon', dialCode: '961' },
  { country: 'Lesotho', dialCode: '266' },
  { country: 'Liberia', dialCode: '231' },
  { country: 'Libya', dialCode: '218' },
  { country: 'Liechtenstein', dialCode: '423' },
  { country: 'Lithuania', dialCode: '370' },
  { country: 'Luxembourg', dialCode: '352' },
  { country: 'Macau', dialCode: '853' },
  { country: 'Macedonia', dialCode: '389' },
  { country: 'Madagascar', dialCode: '261' },
  { country: 'Malawi', dialCode: '265' },
  { country: 'Malaysia', dialCode: '60' },
  { country: 'Maldives', dialCode: '960' },
  { country: 'Mali', dialCode: '223' },
  { country: 'Malta', dialCode: '356' },
  { country: 'Marshall Islands', dialCode: '692' },
  { country: 'Martinique', dialCode: '596' },
  { country: 'Mauritania', dialCode: '222' },
  { country: 'Mauritius', dialCode: '230' },
  { country: 'Mayotte', dialCode: '262' },
  { country: 'Mexico', dialCode: '52' },
  { country: 'Micronesia', dialCode: '691' },
  { country: 'Moldova', dialCode: '373' },
  { country: 'Monaco', dialCode: '377' },
  { country: 'Mongolia', dialCode: '976' },
  { country: 'Montenegro', dialCode: '382' },
  { country: 'Montserrat', dialCode: '1664' },
  { country: 'Morocco', dialCode: '212' },
  { country: 'Mozambique', dialCode: '258' },
  { country: 'Namibia', dialCode: '264' },
  { country: 'Nauru', dialCode: '674' },
  { country: 'Nepal', dialCode: '977' },
  { country: 'Netherlands', dialCode: '31' },
  { country: 'Netherlands Antilles', dialCode: '599' },
  { country: 'New Caledonia', dialCode: '687' },
  { country: 'New Zealand', dialCode: '64' },
  { country: 'Nicaragua', dialCode: '505' },
  { country: 'Niger', dialCode: '227' },
  { country: 'Nigeria', dialCode: '234' },
  { country: 'Niue', dialCode: '683' },
  { country: 'Norfolk Island', dialCode: '672' },
  { country: 'North Korea', dialCode: '850' },
  { country: 'Northern Mariana Islands', dialCode: '1670' },
  { country: 'Norway', dialCode: '47' },
  { country: 'Oman', dialCode: '968' },
  { country: 'Pakistan', dialCode: '92' },
  { country: 'Palau', dialCode: '680' },
  { country: 'Palestine', dialCode: '970' },
  { country: 'Panama', dialCode: '507' },
  { country: 'Papua New Guinea', dialCode: '675' },
  { country: 'Paraguay', dialCode: '595' },
  { country: 'Peru', dialCode: '51' },
  { country: 'Philippines', dialCode: '63' },
  { country: 'Pitcairn Islands', dialCode: '870' },
  { country: 'Poland', dialCode: '48' },
  { country: 'Portugal', dialCode: '351' },
  { country: 'Puerto Rico', dialCode: '1787' },
  { country: 'Puerto Rico', dialCode: '1939' },
  { country: 'Qatar', dialCode: '974' },
  { country: 'Republic of the Congo', dialCode: '242' },
  { country: 'Reunion Island', dialCode: '262' },
  { country: 'Romania', dialCode: '40' },
  { country: 'Russia', dialCode: '7' },
  { country: 'Rwanda', dialCode: '250' },
  { country: 'Saint Barthelemy', dialCode: '590' },
  { country: 'Saint Helena', dialCode: '290' },
  { country: 'Saint Kitts and Nevis', dialCode: '1869' },
  { country: 'Saint Lucia', dialCode: '1758' },
  { country: 'Saint Martin', dialCode: '590' },
  { country: 'Saint Pierre and Miquelon', dialCode: '508' },
  { country: 'Saint Vincent and the Grenadines', dialCode: '1784' },
  { country: 'Samoa', dialCode: '685' },
  { country: 'San Marino', dialCode: '378' },
  { country: 'Sao Tome and Principe', dialCode: '239' },
  { country: 'Saudi Arabia', dialCode: '966' },
  { country: 'Senegal', dialCode: '221' },
  { country: 'Serbia', dialCode: '381' },
  { country: 'Seychelles', dialCode: '248' },
  { country: 'Sierra Leone', dialCode: '232' },
  { country: 'Singapore', dialCode: '65' },
  { country: 'Sint Maarten', dialCode: '1721' },
  { country: 'Slovakia', dialCode: '421' },
  { country: 'Slovenia', dialCode: '386' },
  { country: 'Solomon Islands', dialCode: '677' },
  { country: 'Somalia', dialCode: '252' },
  { country: 'South Africa', dialCode: '27' },
  { country: 'South Korea', dialCode: '82' },
  { country: 'South Sudan', dialCode: '211' },
  { country: 'Spain', dialCode: '34' },
  { country: 'Sri Lanka', dialCode: '94' },
  { country: 'Sudan', dialCode: '249' },
  { country: 'Suriname', dialCode: '597' },
  { country: 'Svalbard', dialCode: '47' },
  { country: 'Swaziland', dialCode: '268' },
  { country: 'Sweden', dialCode: '46' },
  { country: 'Switzerland', dialCode: '41' },
  { country: 'Syria', dialCode: '963' },
  { country: 'Taiwan', dialCode: '886' },
  { country: 'Tajikistan', dialCode: '992' },
  { country: 'Tanzania', dialCode: '255' },
  { country: 'Thailand', dialCode: '66' },
  { country: 'Timor-Leste (East Timor)', dialCode: '670' },
  { country: 'Togo', dialCode: '228' },
  { country: 'Tokelau', dialCode: '690' },
  { country: 'Tonga Islands', dialCode: '676' },
  { country: 'Trinidad and Tobago', dialCode: '1868' },
  { country: 'Tunisia', dialCode: '216' },
  { country: 'Turkey', dialCode: '90' },
  { country: 'Turkmenistan', dialCode: '993' },
  { country: 'Turks and Caicos Islands', dialCode: '1649' },
  { country: 'Tuvalu', dialCode: '688' },
  { country: 'Uganda', dialCode: '256' },
  { country: 'Ukraine', dialCode: '380' },
  { country: 'United Arab Emirates', dialCode: '971' },
  { country: 'United Kingdom', dialCode: '44' },
  { country: 'United States', dialCode: '1' },
  { country: 'Uruguay', dialCode: '598' },
  { country: 'US Virgin Islands', dialCode: '1340' },
  { country: 'Uzbekistan', dialCode: '998' },
  { country: 'Vanuatu', dialCode: '678' },
  { country: 'Venezuela', dialCode: '58' },
  { country: 'Vietnam', dialCode: '84' },
  { country: 'Wallis and Futuna', dialCode: '681' },
  { country: 'Western Sahara', dialCode: '212' },
  { country: 'Yemen', dialCode: '967' },
  { country: 'Zambia', dialCode: '260' },
  { country: 'Zimbabwe', dialCode: '263' },
];

export const defaultDialCode = "91";
